name: A workflow for population reporting system
on: push

jobs:
  test:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run unit tests
        run: |
          mvn -Dtest=com.napier.sem.UnitTests test

      - name: Run integration tests
        run: |
          docker build -t database ./db 
          docker run --name testdb -dp 33066:3306 database
          mvn -Dtest=com.napier.sem.IntegrationTests test
          docker stop testdb
          docker rm testdb

  build:
    name: Population Reporting Action
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Compile and package with Maven
        run: | 
          mvn clean package -Dmaven.test.skip=true
          docker compose up --abort-on-container-exit
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ./target/*.jar