name: A workflow for population reporting system
on: push

jobs:
  build:
    name: Population Reporting Action
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Start MySQL Container
        run: |
          docker run -d --name test-db -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=population -e MYSQL_USER=root -e MYSQL_PASSWORD=password mysql:latest

      - name: Wait for MySQL Database
        run: |
          until docker exec test-db mysqladmin ping -h"localhost" --silent; do
            echo "Waiting for MySQL...";
            sleep 2;
          done

      - name: Run Tests
        run: mvn test
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: password

      - name: Stop and Remove Test Database Container
        run: |
          docker stop test-db
          docker rm test-db
        if: success() # Only stop if tests succeeded

      - name: Compile and Package with Maven
        run: mvn clean package
        if: success() # Only package if tests passed

      - name: Run Docker Compose
        run: docker compose up -d
        if: success() # Only start Docker Compose if package succeeded