name: A workflow for population reporting system
on: push

jobs:
  build:
    name: Population Reporting Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Compile and package with Maven
        run: mvn clean package -Dmaven.test.skip=true

      - name: Run docker compose app
        run: docker compose --network app up -d

      - name: Run tests
        run: docker run --rm --network app -v "mvn -Dtest=com.napier.sem.AppTest test