name: A workflow for population reporting system
on: push

jobs:
  build:
    name: Population Reporting Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run docker compose db
        run: docker compose -f docker-compose-db.yml -p sem29 up -d

      - name: Compile and package with Maven
        run: mvn clean package

      - name: Run docker compose app
        run: docker compose -f docker-compose-app.yml -p sem29 up -d